### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by xbony2**
This PR relicenses this mod under the MIT license. I'm not really sure how relicensing works legally, but I figure if every contributor agrees, then the mod is hence relicensed (I'm not a lawyer, but I've watched _My Cousin Vinny_ a couple times). So, I am asking all of you for your apporval:
* [x] @NanoHeart (original author)
* [x] @xbony2 (porter)
* [x] @ChloeDawn (porter)
* [x] @Lykrast (translator)

### CODE REVIEW

**Comment by ChloeDawn** [comment]
I approve!

**Comment by Lykrast** [comment]
Wait why am I tagged? I think I just did one lang file right?

**Comment by xbony2** [comment]
@Lykrast yes but it's a contribution too :P

**Comment by NanoHeart** [comment]
ye it good

**Comment by Lykrast** [comment]
Ok then you can tick the box with my name. Merry new licence!

**Comment by xbony2** [comment]
Thanks ya'll!

**Pull request merged**
